### ISSUE TITLE
Incompatible with Fargo's Mutant Mod

### ISSUE THREAD

**Issue by ertila007** [ExterminatorX99/MagicStorageExtra#31]
When I was playing the 64-bit version of Tmod Loader, I built first demonite upgrade for my heart system and storage system. I also built an interface for crafting and storage access for upgrading my first buffing chest (that should be the crafting one). But i've also  crafted an item who joined all of basic craftings of early game at once and pulled it next to my heart system. But, when craftings shoulds be occur, nothing was showed for me (whereas itens who should be crafted from workbench should be showed, of anvils too, etc..), and I believe what the reason is for incompatibilities.

Thanks for comprehension.

**Comment by ExterminatorX99** [comment]
Did you place the combined crafting item or did you put it into the crafting interface?

**Comment by ExterminatorX99** [comment]
No response

**Comment by MunchyG** [comment]
>joined all of basic craftings of early game at once and pulled it next to my heart system. 
My guess is "pulled" is supposed to be placed. In which case, yer don't think it is your issue, unless that a feature I was completely unaware of.
