### ISSUE TITLE
Multiplayer discovery issues

### ISSUE THREAD

**Issue by KitsuneNoNatsu** [ExterminatorX99/MagicStorageExtra#34]
Not 100% a bug, but it would be nice if the Item Checklist mod could be server sided in a way that it allows all players to update the checklist if you or another player have discovered something
For instance, it's quite annoying to have to give everyone on the server 1 piece of hellstone ore in order for them all to craft hellstone bars

**Comment by ExterminatorX99** [comment]
Why are you asking me this?
Ask the Item Checklist dev.
https://github.com/JavidPack/ItemChecklist

**Comment by KitsuneNoNatsu** [comment]
Because you recompiled the mod to work with your version of Magic Storage

Get BlueMail for Android<https://bluemail.me>
On Jul 6, 2021, at 19:38, Kristijan Kos ***@***.******@***.***>> wrote:

Why are you asking me this?
Ask the Item Checklist dev.
https://github.com/JavidPack/ItemChecklist

**Comment by ExterminatorX99** [comment]
Well yes, but that was just copy pasting the already existing Magic Storage(original) integration code and changing a few lines.
If you want new features in the mod tell the original dev to add them.
If a new update for Item Checklist comes out, I'll update the recompiled version
