### ISSUE TITLE
i am confused

### ISSUE THREAD

**Issue by imadtg** [ExterminatorX99/MagicStorageExtra#36]
i installed this mod but it didn't work, i came here and saw it was a fork of the original so i thought I'd need to disable it, and that broke the mods dependent on the original, i am confused, how does one install this mod properly?

**Comment by ExterminatorX99** [comment]
The original and this fork are not interchangeable.
This means if a mod depends on the original you need to use the original. You can't substitute it with this fork.
You could use both at the same time, but the ensuing confusion is out of my hands
