### ISSUE TITLE
Broke UI and unable to craft

### ISSUE THREAD

**Issue by Ragerock** [ExterminatorX99/MagicStorageExtra#43]
Using v0.5.4.1 I have tested the storage crafting interface and the search bar was covered in a red diagonal gradient, then it turned  completely black, and no crafting recipes show up even with wood in storage and a work bench in the crafting interface. At least a wooden sword should show up, but there was nothing. I disabled every mod except magic storage extra but the issue remained.

**Comment by ExterminatorX99** [comment]
I'm unable to reproduce this.
Could you please send your mod list and logs?

**Comment by Ragerock** [comment]
It seems restarting the game and reinstalling the mod fixed it somehow. I restarted it to have a shorter log for you to look at, because the one I had was running for a while already when I was using other mods and stuff before I discovered magic storage extra. But doing so seems to have solved my problem.
