### ISSUE TITLE
An error while loading MagicStorageExtra

### ISSUE THREAD

**Issue by TacoStamp** [ExterminatorX99/MagicStorageExtra#46]
Hello. I can not seem to get the mod to work at all on my server. Even having it as the only mod, it will load the world let me in and have 0 mods activated. When I go and look my JSON file will go from:
[
"MagicStorageExtra"
]
to:
[
]

If anyone knows how to fix this it would be greatly appreciated. I've been paying for a server for 2 months trying to get this to work. (I'm bad at procrastination)
There is an error but the console deletes it for some reason when I try and copy it. I was able to get this screen shot though.
![Capture](https://user-images.githubusercontent.com/89282195/130302912-503c7d40-cdea-4140-98a0-53082998d087.PNG)

**Comment by ExterminatorX99** [comment]
I am unable to replicate this.
Could you try deleting then reinstalling MSE and, if you have it, RecursiveCraft?

**Comment by TacoStamp** [comment]
So just a little bit more context I am trying this on my server.  Single player works fine.  Regardless I did what you asked and deleted my MSE file and redownloaded it.  It is the only mod on the server.  I still get this error. 
![Capture](https://user-images.githubusercontent.com/89282195/130402255-de24c4d3-d548-409b-b899-6b9de4011d61.PNG)

**Comment by TacoStamp** [comment]
Ok. I was talking to my friend about this and was wondering why you were asking about RecursiveCraft as I have never had that mod.  I found it in the mod browser and put it on the server with MSE and recipebrowser (just so i could quickly make sure it was there) and it works.  No error.  So I'm not sure why I needed it but I guess that fixed it.

**Comment by ExterminatorX99** [comment]
You're not supposed to need it. It's supposed to be an optional dependency.
This is definitely a bug.
Am I right to assume this is a Linux server?

**Comment by TacoStamp** [comment]
No it shouldn't be as far as I know.  I am renting it through Bisect Hosting.

**Comment by ExterminatorX99** [comment]
Bisect hosts Terraria servers on Linux

**Comment by ExterminatorX99** [comment]
![image](https://user-images.githubusercontent.com/16169502/130492977-1e644949-11a6-4bee-80c3-65a398f5dfbc.png)

**Comment by TacoStamp** [comment]
Yes, they replied to me as well.  Is this why I needed RecursiveCraft?

**Comment by TacoStamp** [comment]
I did and got this error below.  It is causing Fargo's Mutant mod to error out as well now.  
![Capture](https://user-images.githubusercontent.com/89282195/130672031-0ca245cd-7e13-4fc3-9a68-cd9e1fa5a1a6.PNG)

**Comment by ExterminatorX99** [comment]
Does it load without Fargo's?

**Comment by TacoStamp** [comment]
i put recursive craft on and both mods are working fine again

**Comment by TacoStamp** [comment]
no i lied

**Comment by TacoStamp** [comment]
![Capture2](https://user-images.githubusercontent.com/89282195/130673490-6f327c8a-fb79-4dc9-90da-43a8499e1eec.PNG)

**Comment by TacoStamp** [comment]
this is my magic storage now

**Comment by ExterminatorX99** [comment]
You didn't enable MSE

**Comment by TacoStamp** [comment]
nope lol just realized it too.  It was but i guess if there is any error it takes it off the enable.json file and i forgot this fact.

**Comment by TacoStamp** [comment]
but regardless i still seem to need recursive craft to run MSE

**Comment by ExterminatorX99** [comment]
If you disable everything except MSE does it load?

**Comment by TacoStamp** [comment]
no

**Comment by ExterminatorX99** [comment]
Could you send the error that happens?

**Comment by ASterle** [comment]
I get the same error (recursive craft integration) even with RecursiveCraft added. I'm also on Linux and using 64bit tModLoader.

**Comment by ExterminatorX99** [comment]
Fixed in newest version
