### ISSUE TITLE
Storage interface doesn't display unstackable items as stacks unlike regular MagicStorage

### ISSUE THREAD

**Issue by LunarLambda** [ExterminatorX99/MagicStorageExtra#48]
In Magic torage, if you have multiple of the same weapon, accessory, vanity, etc, it only shows that item once as a stack. Magic Storage Extra doesn't do this and displays every duplicate separately. Is this deliberate?

**Comment by coachl4d2** [comment]
Would like to know as well because this is very frustrating from the original, but love the other changes.
