### ISSUE TITLE
Terraria crushing when storage unit below storage heart being destroyed

### ISSUE THREAD

**Issue by jhnazar** [ExterminatorX99/MagicStorageExtra#56]
After v0.5.5.6 update my storage started destroying yourself and crushing terraria after i dismantle storage below storage heart level or when i crafting in multiplayer session or after opening doors. I cannot place storage heart/units above blocks and under storage units too, but i can place them below storage heart or unit. It normally works, but lower empty storage units does not have immunity to be destroyed than can lead to crushing terraria. 
https://youtu.be/BIRla0le_qo
https://youtu.be/oI7d_TSTHLE (played on russian language. Multiplayer server just crushed. Tested with vanilla doors and they have same problem)

**Comment by ExterminatorX99** [comment]
Try the new version and tell me if it's fixed

**Comment by jhnazar** [comment]
It works fine. Thx
