### ISSUE TITLE
Linux 64 bit server loading error - RecursiveCraft Integration

### ISSUE THREAD

**Issue by Abukes01** [ExterminatorX99/MagicStorageExtra#60]
I'm having problems with the mod on a very large pack I'm trying to put a server on for me and my friends. This happens on Linux tModLoader64BitServer version, running the latest versions of server and mods.

What happens:
Server loads mods, and first there's a conflict with Hamstar Helpers that logs the MagicStorageExtra function calls
![image](https://user-images.githubusercontent.com/51299415/135680787-26fadc58-fb60-4ffe-b2b2-12ca2b31c86b.png)

Then server reloads with HH disabled, and another error occurs, this time with MSE RecursiveCraft integration
![image](https://user-images.githubusercontent.com/51299415/135681005-a04bb434-a7b6-46bc-b1db-3b5120a91cf2.png)

Nothing I tried helped get rid of this issue, tried reinstalling the mods from server browser, same happened; tried with and without RecursiveCrtaft installed, same happened; This also occurred while trying to load only MSE and Recursive Craft:
![image](https://user-images.githubusercontent.com/51299415/135681461-5a9dcf5d-49d7-4a15-993b-4d3cac8b40fa.png)

This only started happening after I updated the mod from a version without the integration, and until this gets fixed I can't access my world (and the mod is incompatible with vanilla Magic Storage (I don't have any way as of writing this to transfer files from my remote server, working on setting up sftp).

Looking forward to see an update or some way to work around this.

**Comment by Abukes01** [comment]
I'm running Linux Mint 20.1 with latest available complete Mono package for the server.

**Comment by maxsupermanhd** [comment]
Happened to me however it solved itself by loading regular MagicStorage and then disabling it somehow

**Comment by ExterminatorX99** [comment]
Fixed in newest version
