### ISSUE TITLE
Storage not retaining selection

### ISSUE THREAD

**Issue by MrMetaMeme1** [ExterminatorX99/MagicStorageExtra#64]
The storage heart and crafting terminal are not retaining selections such as the selection of craftable recipes only, storage units from MagicStorageExtra don't work with storage units from MagicStorage they are craftable yet not compatible with each other (not sure if that is intended).

**Comment by MunchyG** [comment]
The 2 mods are not designed to work together (as blocks) but MSE added compatibly to craft things using MS items. Also don't think saving the selection is a feature, but I could be wrong.

**Comment by ExterminatorX99** [comment]
There's a config for saving the selection

**Comment by MrMetaMeme1** [comment]
Where is the config for the saving the selection exactly?
