### ISSUE TITLE
a bug by JoJoStands mod conflict

### ISSUE THREAD

**Issue by ume21ume** [ExterminatorX99/MagicStorageExtra#65]
I found a bug that is mod conflict when I was playing tModLoader 64bit (ver, 0.11.8.5).

It is like this (https://youtu.be/y1Sbmzolk88).
mod:
･CheatSheet
･JoJoStands
･MagicStorageExtra

Please fix this bug.

**Comment by ExterminatorX99** [comment]
Does this happen with only MSE enabled?

**Comment by ume21ume** [comment]
No, I enabled MSE, JoJoStands, and CheatSheet.

**Comment by ExterminatorX99** [comment]
If disabling JoJoStands solves it, it's a problem on their end

**Comment by ume21ume** [comment]
I know it.
would you fix the MagicStorageExtra's bug with JoJoStands, please?
I want to use both in the same play.

**Comment by ume21ume** [comment]
maybe, I should tell this bug author of JoJoStands mod...

**Comment by ume21ume** [comment]
if you are not able to fix this bug, Maybe I should tell this bug author of JoJoStandsmod.

**Comment by ume21ume** [comment]
oh no
i made a mistake...

**Comment by ExterminatorX99** [comment]
This isn't an `MSE` bug. It's a `JoJoStands` bug

**Comment by ume21ume** [comment]
ok, I will ask author of JoJoStands mod.
thank you.
