### ISSUE TITLE
Recursive craft not working

### ISSUE THREAD

**Issue by maxsupermanhd** [ExterminatorX99/MagicStorageExtra#70]
I have latest release of MSE (0.5.5.9) on `Terraria Server v1.3.5.3 - tModLoader v0.11.8.5` and I am playing on my server with a friend, we don't see any recursive craft working.
Modlist:
```
Calamity Mod (No Calamity Music)
Lan's Shared Map [Beta]
Magic Storage
Recursive Craft
Magic Storage - Extra
Thorium Mod
```
Items that can be crafted with recursive craft are unavailable.
![image](https://user-images.githubusercontent.com/20772987/146078065-a9d502be-b853-4ef2-84ae-07018c793dd9.png)
![image](https://user-images.githubusercontent.com/20772987/146078092-c2137786-3cf8-43b9-b0a8-468c75dd7882.png)

**Comment by ExterminatorX99** [comment]
I assume you have a hardmode anvil in the crafting stations.
Does it work if you place the anvil in world and have the items in your inventory?

**Comment by maxsupermanhd** [comment]
Yes, vanilla menu has recursive crafting working.

**Comment by ExterminatorX99** [comment]
Wait a second. You're using regular Magic Storage. Not Extra
They're separate mods. Extra is not an addon. It's standalone

**Comment by maxsupermanhd** [comment]
If I disable Magic Storage it wount load up because it is missing a recursivecraft version 1.0 or something similar

**Comment by ExterminatorX99** [comment]
Are you on linux?

**Comment by maxsupermanhd** [comment]
Yes, and looks like issue #60...
