### ISSUE TITLE
Possible solution for crafting interface lag?

### ISSUE THREAD

**Issue by Jacklz** [ExterminatorX99/MagicStorageExtra#76]
Issue: The crafting interface lags both with and without recursive craft when there are a lot of recipes to calculate.

Solution: Not sure how plausible this would be but its an idea; Offload the recipe calculations to have the server perform them and send the results back as a mod packet? This way the client doesn't have a massive drop in fps and is still able to search through recipes with ease. Of course this would only be a multiplayer solution as single player wouldn't be able to offload the calculations to a server.

**Comment by ExterminatorX99** [comment]
Unfortunately, at least from my knowledge, calculating recipes is exclusively client side
