### ISSUE TITLE
MagicStorage + MS - Extra & SGAMod - Empty Soul Jar put into MS storage prevents world from loading

### ISSUE THREAD

**Issue by Xemgoa** [ExterminatorX99/MagicStorageExtra#77]
Placing the Empty Soul Jar (and I think it's "Soul Jar" state) into Magic Storage - Extra storage and normal Magic Storage prevents the world from loading.

Uninstalling Magic Storage + Extra allows loading the world again, but reinstalling without removing the missing assets for MS + E causes the same state of being unable to load the world.

[client.log](https://github.com/ExterminatorX99/MagicStorageExtra/files/7836624/client.log)

**Comment by ExterminatorX99** [comment]
Report this to `SGAmod`

**Comment by Xemgoa** [comment]
@ExterminatorX99 I have done so, they are aware of this.

I reckon it's being looked into, I am letting you know incase you want to check too.

**Comment by ExterminatorX99** [comment]
The error is in their item load code. Not much I can do about that

**Comment by Xemgoa** [comment]
Alright. Thank you for taking a look!

**Comment by IDGCaptainRussia94** [comment]
Yeah this is on my end, Not MagicStorageExtra's, I'll try to resolve it soon
Really sorry, about of this kind of stuff often goes unnoticed during what little testing I get

**Comment by ExterminatorX99** [comment]
No worries. Let me know when it's fixed so I know to close the issue

**Comment by Xemgoa** [comment]
I have done a quick test -- I put an empty soul jar into the Magic Storage - Extra storage.

The world loaded up just fine. HOWEVER, this is just with the empty jar - will edit this message later when trying a "Filled" Soul jar
![MSE-SGAMOD-FilledSoulJar_bug](https://user-images.githubusercontent.com/97420471/148974772-39a075f1-e098-466f-a763-b6cf8f0ea079.png)

I think this can be closed, tho - and this can continue on the SGAMod Discord.

Thank you for your time.

**Comment by IDGCaptainRussia94** [comment]
would appear I (after too many to be honest attempts) have managed to resolve this issue, and unloadable worlds are now able to load fine and dandy!
Issue resolved I'd say
