### ISSUE TITLE
items in the magic storage disappearing

### ISSUE THREAD

**Issue by glacierizer** [ExterminatorX99/MagicStorageExtra#92]
so basically here's what happened. i play with the stars above, fargo mutant, boss cursor, weapon out, starter bag and angler shop mods and when i get back from stars above mod's observatory subworld my magic storage heart was saying like entity not found or something like that. i break it and replace it and it says my storage units aren't connected so i break them and place them back and now everything i had is gone. everything i had. is there a way i can get the items back at least?

**Comment by ExterminatorX99** [comment]
To my understanding Stars Above is a 1.4 tml mod. That means you're definitely not using this mod, you're using the original version of Magic Storage for which you should report issues either on [their discord](https://discord.gg/FemPG7eev4) or [github repo](https://github.com/blushiemagic/MagicStorage)
